version: '3.7'

services:
  template:
    container_name: template
    build:
      context: .
      target: production
      dockerfile: ./docker/Dockerfile
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - template_db
