version: '3.7'

services:
  template_db_test:
    container_name: template_db_test
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
