export const PARAMETERS = {
  HTTP_PORT: 'HTTP_PORT',
  NODE_ENV: 'NODE_ENV',
  CORS_ORIGIN: 'CORS_ORIGIN',
  JWT_IGNORE_EXPIRATION: 'JWT_IGNORE_EXPIRATION',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USER: 'DB_USER',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
  JWT_AUTH_ALGORITHM: 'JWT_AUTH_ALGORITHM',
  JWT_AUTH_PUBLIC_KEY: 'JWT_AUTH_PUBLIC_KEY',
};

export default PARAMETERS;
